---
#- name: create grav group
#  group: name="{{ grav_group }}"

#- name: create grav user
#  user:
#     name: "{{ grav_user }}"
#     comment: "grav cms user"
#     home: "{{ grav_basedir }}"
#     group: "{{ grav_group }}"

- name: download tarball
  get_url: url={{ grav_download_url }} dest=/tmp/grav.zip
#force=true

- name: create web dir
  file:
    path: "{{ grav_basedir }}"
    state: directory
    mode: 0755

- name: extract tar ball
  unarchive:
    src: /tmp/grav.zip
    dest: "{{ grav_basedir }}"
    copy: no
    owner: "{{ grav_user }}"
    group: "{{ grav_group }}"

- name: create link to grav-admin
  file:
    state: link
    src: "{{ grav_basedir }}/grav-admin"
    path: "{{ grav_basedir }}/blog"

- name: ship lighttpd config
  template:
    src: grav.lighttpd.conf.j2
    dest: /etc/lighttpd/conf-enabled/72-grav.conf
    mode: 0644

- name: rollout users
  template:
    src: account.j2
    dest: "{{ grav_basedir }}/blog/user/accounts/{{ item.name }}.yaml"
    owner: 'www-data'
    group: 'www-data'
    mode: '0644'
  loop: "{{ grav_users }}"

